### ISSUE TITLE
Game gets stuck loading a world at 54% (both in a single player world and multiplayer one) and won’t load any further no matter how long I wait

### ISSUE THREAD

**Issue by Am5teur** [Harleyoc1/ChunkAnimator#10]
I’m trying to use this mod in a modpack of mine but I believe it isn’t compatible with one of the mods I have installed since it works fine when on its own

The modpack I’m using is:
https://www.curseforge.com/minecraft/modpacks/almond

it uses version 1.16.5 of Minecraft and forge version 36.0.42 along with version 1.2.3 of chunk animator

**Comment by Harleyoc1** [comment]
Do you mean you've tried uninstalling chunk animator from the pack and it worked? I don't see how it could be causing this because chunk animator doesn't actually do anything until you are loaded into the world (only at that point do chunks begin rendering).

**Comment by Am5teur** [comment]
Yeah, the Modpack works perfectly fine when chunk animator isn’t installed but when chunk animator is installed I can’t load into a world at all. The modpack is linked in the issue submitted, you could try it for yourself and I’d expect you’d get the same result as me.

**Comment by Harleyoc1** [comment]
Right OK, yeah must be some sort of incompatibility. I'll take a look into it.

**Comment by Am5teur** [comment]
Indeed, I hope you’re able find what’s causing the problem.

**Comment by Harleyoc1** [comment]
I noticed immersive portals was in the pack and thought that might be causing it, and it is, removing it stops the issue. I'll take a look into why this is happening.

**Comment by Am5teur** [comment]
Oh, good job finding it! Hopefully it’s an easily fixable problem, also the immersive portals team is pretty responsive, so if it’s an issue that can only be fixed on their side then they might be willing to fix it if the issue is simple.

**Comment by Harleyoc1** [comment]
Seems this isn't the only mod that this is being caused with. Only a couple of days ago someone also reported something similar happening with the Chlorine mod installed. I thought it was somehow caused by us both making changes to the same vanilla class, though I would expect any conflicts from that to just cause a crash. The fact that it also happens with this other mod makes me think it could be a problem on their end.

**Comment by Harleyoc1** [comment]
Also unfortunately seems that they are dropping support for Forge in favour of their Fabric version, so may be difficult to get any response on their end.

**Comment by mrbuilder1961** [comment]
I've been having the same error (with Immersive Portals installed). If it helps, when I load a world this is the error I get:
https://pastebin.com/uVtrJ4qH
It's constantly spammed in the logs, and to close the game you have to force-quit it.

**Comment by DestinyPlayer** [comment]
Can concur that this happens for me as well, with Immersive Portals.
https://www.dropbox.com/s/2qspbnzsz6iow68/latest.log?dl=0 - My log.

Immersive Portals - 0.16-mc1.16.5-forge
Chunk Animator - 1.16.5-1.2.3

**Comment by Harleyoc1** [comment]
That would help a ton (assuming it's being caused by this incompatibility)!

**Comment by Harleyoc1** [comment]
Could someone verify this is not in their logs without Chunk Animator installed? From first look it's difficult to tell if this is related or not and I'd appreciate if someone could verify before I look any further.

**Comment by Harleyoc1** [comment]
Never mind. I just did some more testing and found an even more informative stacktrace leading me to exactly where the problem is.
