### ISSUE TITLE
GUI elements not visible when using version for 1.16.5

### ISSUE THREAD

**Issue by DanysP** [Harleyoc1/ChunkAnimator#11]
**Describe the bug**
Loading into a single player world or multiplayer server will cause GUI elements (hotbar, inventory, escape screen) to be invisible while the mod is in use. Attempting to open the inventory or escape screen will still work, the cursor is visible, and actions can be made, but any sort of GUI is not visible. The player's hands and held items are still visible, and toggling F1 works as intended. I am using the latest version of OptiFine (Ultra G7) and Forge 36.1.0 for 1.16.5 at the time of this report. I have attempted disabling any resource and shader packs, ensuring render regions is disabled, and tested both single player and multiplayer worlds. 

**To Reproduce**
1. Latest version of Chunk Animator with default config installed
2. Launched Minecraft Forge profile
3. Connected to single player or multiplayer world
4. Notice error
5. Confirmed error by toggling F1 and attempting to navigate GUI menus, with no change

**Expected Behavior**
I expected for all game GUI elements to display properly, with OptiFine installed and with shaderpacks and/or resource packs to be loaded or not loaded at the same time.

**Screenshots**

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.0
 - Chunk Animator Version: 1.2.3 for 1.16.5

**Additional context**

**Comment by Harleyoc1** [comment]
I can't reproduce this (with matching versions including OptiFine), and I'm not entirely sure how this could be caused (though rendering can produce weird outcomes like this at times).

Does it only happen when OptiFine is installed and do you have mods other than chunk animator installed/have you tried running without them?
