### ISSUE TITLE
Chunk Animator Not Working

### ISSUE THREAD

**Issue by WhiteGuyGaming** [Harleyoc1/ChunkAnimator#13]
**Describe the bug**
Chunks load in as normal in Minecraft. Chunk animations not working.

**To Reproduce**
I will include a screenshot of the mod list 

**Expected Behavior**
Expected chunks to animate, did not happen. 

**Screenshots**

![Mod List](https://user-images.githubusercontent.com/83326860/117179922-a84eab80-ada1-11eb-9c76-0259e0370ae4.png)

**Versions:**
 - Minecraft Version: 1.16.5
 - Forge Version: 36.1.13
 - Chunk Animator Version: 1.2.4

**Comment by Harleyoc1** [comment]
You have OptiFine installed. Please see #3 - you need to make sure render regions is turned off in `Video Settings -> Performance`.

**Comment by WhiteGuyGaming** [comment]
Yep, that fixed it. Unfortunately, I need render regions to keep a stable FPS with no stuttering. Ah well. It is a nice mod though.
