### ISSUE TITLE
One of the config settings doesn't work.

### ISSUE THREAD

**Issue by GitHubKingOJA** [Harleyoc1/ChunkAnimator#14]
The config option to not have animations on the chunks right below/around your c haracter does not work. Making it still have time where there is no chunk under your character loaded even when changing that option to true and clicking save.

**Comment by Harleyoc1** [comment]
Please state your versions as requested by the bug report template.

**Comment by GitHubKingOJA** [comment]
My version is 1.16.5.

**Comment by Harleyoc1** [comment]
And you're definitely on latest Chunk Animator (currently 1.2.4 for 1.16.5)?

**Comment by GitHubKingOJA** [comment]
Yes

**Comment by GitHubKingOJA** [comment]
I downloaded the day I made the github issue since thats when I found the issue.

**Comment by Harleyoc1** [comment]
Works fine for me. Note that it will not stop an animation that has already started so when you're flying around they might sometimes animate under you if you are flying too fast but shouldn't be a problem if your computer can load chunks at a decent speed. 

I'm going to close this for now but if you think this is still an issue then please do re-open.
