### ISSUE TITLE
Crash java.lang.VerifyError: Bad local variable type

### ISSUE THREAD

**Issue by LadFlaver** [Harleyoc1/ChunkAnimator#15]
[Crash Report](https://gist.github.com/Harleyoc1/535c25245dc8bbd6d9285efced781f9b)

**Comment by Harleyoc1** [comment]
I don't believe this to be a Chunk Animator problem in itself. Looks to me like one of the other mods is changing the local variables in the function we are applying a core mod to (which is a very stupid thing to do). I suggest you attempt to narrow it down to the mod that is causing it and report it to them.

**Comment by Harleyoc1** [comment]
Never mind. I just realised you're using OptiFine. They don't support Forge yet in 1.17.

**Comment by LadFlaver** [comment]
I'm using a forge/optifine compatibility mod.

**Comment by caseykueltzo** [comment]
Hello,
Optifine has been updated to work with Forge 1.17.1 - 37.0.65.
I'm receiving this issue though
thanks
[crash-2021-10-02_22.16.35-client.txt](https://github.com/Harleyoc1/ChunkAnimator/files/7272621/crash-2021-10-02_22.16.35-client.txt)

**Comment by Mathue24** [comment]
Having the same issue here
[crash-2021-10-03_13.30.13-client.txt](https://github.com/Harleyoc1/ChunkAnimator/files/7273227/crash-2021-10-03_13.30.13-client.txt)
