### ISSUE TITLE
water floats in sky?

### ISSUE THREAD

**Issue by headhuntercertified** [Harleyoc1/ChunkAnimator#19]
water seems to float up into the sky visually client side, but cever side water is in coorect place but invisible until swimming

**Comment by Harleyoc1** [comment]
Please add some context. i.e. 
- MC, Forge, CA version
- OptiFine? (if yes, add version)

**Comment by headhuntercertified** [comment]
![Screenshot (46)](https://user-images.githubusercontent.com/95041066/145596140-5894179f-9a44-41bc-af54-1bab1025f31d.png)
i will try and get a screen shot of my issue

**Comment by headhuntercertified** [comment]
iv since taken chunk animator out, but will return it too try and reproduce the issue

**Comment by headhuntercertified** [comment]
![2021-12-11_02 16 57](https://user-images.githubusercontent.com/95041066/145598071-0446c30a-1093-46fe-b89e-e9e3ecc3547c.png)

**Comment by headhuntercertified** [comment]
![2021-12-11_02 16 47](https://user-images.githubusercontent.com/95041066/145598166-99637af2-bb3e-4262-85a3-2fb4a3b6534d.png)

**Comment by RaptaG** [comment]
I have the same issue too
