### ISSUE TITLE
Is this going to be published on CurseForge?

### ISSUE THREAD

**Issue by koderian** [Harleyoc1/ChunkAnimator#2]
Is this going to be published on CurseForge with the 1.16.5 port?

**Comment by Harleyoc1** [comment]
From my PR: I think I made a mistake releasing a build on here, if I can’t get in contact with lumien in the next couple of days about merging and releasing this on the original CurseForge page then I will create a separate one for my fork.

I still haven’t gotten any response from lumen so I’ll likely be uploading this on a separate CurseForge page later today.

**Comment by koderian** [comment]
It's uploaded! Great!
