### ISSUE TITLE
ChunkAnimator not working with Optifine

### ISSUE THREAD

**Issue by ghost** [Harleyoc1/ChunkAnimator#20]
**Describe the bug**
Chunks generate like in vanilla MC despite render regions being off along with testing other options

**To Reproduce**
1. Have Optifine installed
2. Have any of the performance settings on or off, specifically render regions
3. See error

**Expected Behavior**
Chunks supposed to generate using the mod.

**Versions:**
 - Minecraft Version: [e.g. 1.18] 
 - Forge Version: [e.g. 38.0.14]
 - OptiFine [1.18_HD_U_H3]

**Comment by realqdbp** [comment]
But only if playing with shaders.

I have optifine installed on 1.18, everything works.
But when I use a shader eg. Complementary, it does no longer!

**Comment by grumblerbear** [comment]
shaders off, but get same issue

**Comment by MattressCo** [comment]
> 

I am having the same issue, wiht optifine shaders chunks do not animate, however without shaders they work fine
this is using Complementary Shaders for 1.18.1

**Comment by MattressCo** [comment]
I have tested this with 5 different shaders, each time i use a shader the chunks do not animate however once i turn off shaders the chunks animate fine, render regions is definetly off.

**Comment by MattressCo** [comment]
The shaders i tested with were:

- BSL
- Complementary Shaders
- Continuum
- Nostalgia
- Oceano Shaders

**Comment by epic4gaming8** [comment]
Same problem, render regions are off, and no shaders on, still not working. Here's my settings if it can help: 
![image](https://user-images.githubusercontent.com/80875391/150909444-f6aee7d3-6f2c-486f-b045-77ce099fa085.png)
Version is: Optifine HD U H4, 1.18.1
