### ISSUE TITLE
Chunks always load in from above when below Y=0

### ISSUE THREAD

**Issue by gaforb** [Harleyoc1/ChunkAnimator#22]
Chunks located below Y=0 will always load in from above, regardless of config settings.

Versions:
 - Minecraft Version: 1.18.1
 - Forge Version: 39.0.79
 - Optifine Version: 1.18.1 HD U H4
 - Chunk Animator Version: 1.18-1.3.3
 
 (Side note - Mod works fine with the latest optifine if both Shaders and Render Regions are disabled.)

**Comment by Harleyoc1** [comment]
I suspect this is a result of me forgetting they changed the world height in 1.18. IIRC it assumes the world has a min of Y=0 instead of computing it dynamically.
