### ISSUE TITLE
Crash on latest version 1.18.2-1.3.4

### ISSUE THREAD

**Issue by InteJason** [Harleyoc1/ChunkAnimator#25]
Possible incompatibilities with Rubidium?

https://paste.ee/p/l7qi6

**Comment by tankyap** [comment]
have same issue

**Comment by DeleteMetaInf** [comment]
I have the same issue as well. Seems to be the same cause as well.

**Crash report:** https://pastebin.com/raw/9aaZZ1R1
**latest.log:** https://pastebin.com/raw/42FTtXm1

#### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (version 0.4.25—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Chunk Animator:** 1.3.4 (latest for 1.18.2)
* **Rubidium:** 0.5.3 (latest for 1.18.2)

<details>
  <summary>Client-side mods I added to ATM 7 (click to expand)</summary>
  
3D Skin Layers, Armor Status HUD Renewed, Ambient Environment, AmbientSounds, Better Animal Models, Better Biome Blend, BetterFoliage Renewed, BetterFPS Render Distance, Better Mods Button, Better Third Person, Boat Item View, BobLib, CarrotsLib, **Chunk Animator**, ClearDespawn, CreativeCore, Drip Sounds, Effective, ExperienceBugFix, FirstPerson Model, Improved Mount HUD, Inventory Essentials, Inventory Spam, InvMove, InvMoveCompats, ItemBorders, Krypton, Nimble, Not Enough Animations, Oculus, PuzzlesLib, Random Block Placement, RebindNarrator, **Rubidium**, SignTools, Simple Text Overlay, Sound Physics, Starlight
</details>

**Comment by Nevrai** [comment]
I have the same issue as well. Seems to be the same cause as well.

**Crash report:** https://pastebin.com/raw/9aaZZ1R1
**latest.log:** https://pastebin.com/raw/42FTtXm1

It is unclear whether this is a conflict between Chunk Animator and Rubidium, as the crash report and latest.log don’t seem to have any indication that this is the case, but it seems likely considering #24 and #16.

#### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (version 0.4.25—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **Chunk Animator:** 1.3.4 (latest for 1.18.2)
* **Rubidium:** 0.5.3 (latest for 1.18.2)

<details>
  <summary>Client-side mods I added to ATM 7 (click to expand)</summary>
  
3D Skin Layers, Armor Status HUD Renewed, Ambient Environment, AmbientSounds, Better Animal Models, Better Biome Blend, BetterFoliage Renewed, BetterFPS Render Distance, Better Mods Button, Better Third Person, Boat Item View, BobLib, CarrotsLib, **Chunk Animator**, ClearDespawn, CreativeCore, Drip Sounds, Effective, FirstPerson Model, Improved Mount HUD, Inventory Essentials, Inventory Spam, InvMove, InvMoveCompats, ItemBorders, Nimble, Not Enough Animations, Oculus, PuzzlesLib, Random Block Placement, RebindNarrator, **Rubidium**, SignTools, Simple Text Overlay, Sound Physics, Starlight

And Krypton Reforged, which is the only server-side one.
</details>

**Comment by Nevrai** [comment]
Having exactly the same crash in 1.19.2.

**Crash report:** https://pastebin.com/raw/xMiyGyWw

### Versions
* **Minecraft:** 1.19.2 (latest)
* **Forge:** 43.1.25 (latest)
* **Chunk Animator:** 1.3.5 (latest)

**Comment by Harleyoc1** [comment]
Duplicate of #24
