### ISSUE TITLE
Optifine Crash (InvocationTargetException)

### ISSUE THREAD

**Issue by EinJOJO** [Harleyoc1/ChunkAnimator#31]
**Describe the bug**
Even though `ofRenderRegions`  is set to false, it crashes on startup.

**To Reproduce**
Client: Forge, Optifine, Chunkloader
smash (start),
crash.

**Expected Behavior**
The client starts lmao,

**Versions:**
 - Minecraft Version: 1.19.1 
 - Forge Version: 42.0.9
 - ChunkAnimator-1.19.1-1.3.5
 - OptiFine HD U H9 (released 20.08.22)

**Additional context**
Crash log https://hastebin.com/habuvehimo.yaml

**Comment by Harleyoc1** [comment]
Duplicate of #28
