### ISSUE TITLE
Chunk Animator Not Animating with Shaders

### ISSUE THREAD

**Issue by Vatruvius** [Harleyoc1/ChunkAnimator#32]
**Notice**
If you are opening an issue **for any other reason** than to report a bug or request a new feature, you should probably be using the [Discussions](https://github.com/Harleyoc1/Chunk-Animator/discussions) tab.

**Describe the bug**
Chunk Animator does not animate when any shader besides OptiFine Internal is enabled.

**To Reproduce**
1. Have OptiFine installed.
2. Load any shader besides Internal in OptiFine.
3. Chunks no longer animate.

**Expected Behavior**
Chunks animate while shader is loaded in OptiFine.

**Versions:**
 - Minecraft Version: 1.18.2
 - Forge Version: 40.1.74
 - Chunk Animator Version: 1.3.4
 - OptiFine Version: 1.18.2 HD U H9 Pre1

**Additional context**
#26

**Comment by Vatruvius** [comment]
Animations remain broken when loading any shader pack. I used Sildur's Shader Version 1.41 since it was updated.

**Comment by Harleyoc1** [comment]
Fixed in 1.3.7. Make sure render regions is off as it is still incompatible with this option.
