### ISSUE TITLE
Compability problem with shaders

### ISSUE THREAD

**Issue by Crown-Fairy** [Harleyoc1/ChunkAnimator#35]
**Describe the bug**
The chunk animation didn't work when shader was loaded.

**To Reproduce**
1. Have Optifine installed

**Expected Behavior**
It should still run with the shader loaded.

**Versions:**
 - Minecraft Version: [e.g. 1.18.2] 
 - Forge Version: [e.g. 40.2.2]
 - Chunk Animator Version: [e.g. 1.3.4]

**Comment by Ihsan101** [comment]
Already fixed in version 1.3.7. I do not think older versions will get this update.

**Comment by Harleyoc1** [comment]
Please provide what version you're running @Crown-Fairy.

**Comment by Crown-Fairy** [comment]
> Please provide what version you're running @Crown-Fairy.
1.18.2
Chunk Animator:1.3.4
