### ISSUE TITLE
Falling Block Entities are invisible

### ISSUE THREAD

**Issue by TrashCasterMage** [Harleyoc1/ChunkAnimator#40]
**Describe the bug**
Falling block entities (sand, gravel, anvils) are invisible while using this mod in 1.20.1.

**To Reproduce**
1. Have ChunkAnimator installed alongside **Minecraft 1.20.1** and **Forge 47.2.0**.
2. Place gravel, sand, or some other falling block.
3. While falling, the block entity will become invisible.

**Expected Behavior**
The falling block should be visible.

**Screenshots**
I could, but it wouldn't show much.

**Versions:**
 - Minecraft Version: 1.20.1
 - Forge Version: 47.2.0
 - Chunk Animator Version: 1.3.7

**Additional context**
Issue reproducible on my end with a fresh minecraft/forge install where this is the only mod.

**Comment by bloodmasked** [comment]
same thing happens to me, sand and gravel just fall instantly with no animation in between
