### ISSUE TITLE
Discovered : ChunkAnimator not working when TextFix mod is installed

### ISSUE THREAD

**Issue by nveXyounes** [Harleyoc1/ChunkAnimator#42]

**Comment by Harleyoc1** [comment]
Please provide versions affected and in what way it is 'not working' - i.e. does the game crash, not animate chunks, etc.

**Comment by nveXyounes** [comment]
> This issue has gone stale. Please reply again if this is still an issue.

i made a mistake sorry, when i relaunched the game everything works fine.

**Comment by nveXyounes** [comment]
> Please provide versions affected and in what way it is 'not working' - i.e. does the game crash, not animate chunks, etc.

i made a mistake sorry, when i relaunched the game everything works fine.
