### ISSUE TITLE
EXTREME FPS impact when Chunk Animator 1.16.5 is enabled

### ISSUE THREAD

**Issue by koderian** [Harleyoc1/ChunkAnimator#5]
**Notice**
When Chunk Animator is enabled, the game has extreme lag spikes, FPS drops, and generally very low FPS. I tested to see if this was a issue with Optifine, but even without Optifine Chunk Animator causes absurd performance issues. 

**Describe the bug**

When Chunk Animator is enabled, the game has extreme lag spikes, FPS drops, and generally very low FPS. I tested to see if this was a issue with Optifine, but even without Optifine Chunk Animator causes absurd performance issues. 

**To Reproduce**
Use my modpack:
https://www.curseforge.com/minecraft/modpacks/wildhalla/files/3207837
I allocaed 6GB of ram. 

**Expected Behavior**
Expected behavior is for chunk animator when enabled to not cause performance issues. 
**Screenshots**

**Versions:**
 - Minecraft Version: [e.g. 1.16.5] 1.16.5
 - Forge Version: [e.g. 36.0.31] 36.0.42
 - Chunk Animator Version: [e.g. 2.1] 1.2.0

**Additional context**
I know it's Chunk Animator because as soon as I disabled it and relaunched the game the FPS was consistent and had little to no drops. 

Here is the modlist: https://www.modpackindex.com/modpack/27583/wildhalla

**Comment by Harleyoc1** [comment]
It’s using the same algorithm as 1.12, so performance impact **should** be proportionately the same, which is to say very little. I will see what I can do about optimising it and I’ll do some debugging to make sure nothing is going wrong to cause this anyway.

**Comment by Harleyoc1** [comment]
In my testing I didn’t notice any “extreme FPS impact”, in fact my FPS was almost identical to what it was without the mod. It’s possible one of the other mods in your pack is doing something to cause chunk animations to lag, but I can’t see how. Might be worth seeing if you notice any FPS difference when playing without any other mods. Another thing to try might be playing around with your java arguments. 

I’ve made some (very slight) performance improvements (if that even), but I can’t really find anything else to do. Maybe I’ll think of something eventually but without changes to how Minecraft renders chunks normally (which I think is out of scope for this mod) I don’t think there’s anything else I can do, so I’m going to close this for now.
